language: go

go:
  - 1.5.3
  - 1.6
  - tip

env:
  - GOOS=darwin
  - GOOS=windows
  - GOOS=linux

# let us have speedy Docker-based Travis workers
sudo: false

install:
  # Symlink below is needed for Travis CI to work correctly on personal forks of swarm
  - ln -s $HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG///swarm/} $HOME/gopath/src/github.com/docker
  - export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
  - export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/GeertJohan/fgt

script:
  - script/validate-gofmt
  - go vet ./...
  - golint ./...
  # Lint shell files and make sure they are not space indented.
  - fgt find test/ -type f \( -name "*.sh" -or -name "*.bash" -or -name "*.bats" \) -exec grep -Hn -e "^ " {} \;
  - go version
  - go build
  - go test -v -race ./...
